engagement-dashboard.js
locales/en.js

Change title to "Engagement Dashboard" (localized), put title in a `h1`, add L/R padding
Quality notes
* UX/Docs: see screenshots
* other: N/A
Larger than 615px: L/R padding = 30px
Smaller than 615px: L/R padding = 18px
Really small: title text isn't overlapping (which was the default)
@johngwilkinson @hyehayes @MykolaGalian @rohitvinnakota

Minor cosmetic changes

---

components/dropdown-filter.js
locales/en.js
package.json
test/components/dropdown-filter.test.js

[US119136](https://rally1.rallydev.com/#/detail/userstory/410073841016?fdp=true): [Engagement][Filters] Replace simple-filter with facet-filter-sort component
This PR introduces `d2l-insights-dropdown-filter` component that I'm going to use instead of `d2l-simple-filter` to achieve all AC in the story. `d2l-insights-dropdown-filter` uses Gaudi's `d2l-filter-dropdown` component under the hood
PR Draft with changes to existing Semester and Role filters: https://github.com/Brightspace/insights-engagement-dashboard/pull/26 
-  Tests
- Browsers
NB. This PR does not change `Semesters` and `Roles` filter

US119136  [Engagement][Filters] Replace simple-filter with facet-filter-sort component. New app level filter component

---

components/role-filter.js
components/semester-filter.js
engagement-dashboard.js
model/data.js
model/fake-lms.js
model/lms.js
test/components/role-filter.test.js
test/model/lms.test.js

Moving some things around and renaming others. I also "de-classed" LMS and FakeLMS because I wanted to be able to use the functions statically.
Testing: 
* Still works as before on Chrome, Edge Legacy
* Hardcoding OrgUnit ids into `lms.fetchData` fetched the correctly filtered data from the server. Tested with a Department, a Course Template and a Course Offering. OU filter is updated based on `serverData.selectedOrgUnitIds`
@MykolaGalian @rohitvinnakota @hyehayes @anhill-D2L

US118248 Refactoring, groundwork for calling server with filter params

---

model/data.js

TODO: 
Quality notes
* Testing
* Using the demo page (`npm start`) it now counts the number of users with overdue assignments based on the filtered selection, instead of using the whole serverData list.
@Vitalii-Misechko @anhill-D2L @rohitvinnakota @hyehayes

GetRecordsInView uses filtered records instead of serverData

---

engagement-dashboard.js
model/data.js
model/orgUnitAncestors.js
model/selectorFilters.js
package.json
test/components/users-table.test.js
test/model/data.test.js
test/model/orgUnitAncestors.test.js
test/model/selectorFilters.test.js

Reloads data from server based on logic in [the org unit spike](https://rally1.rallydev.com/#/23525809118d/workviews?detail=%2Fuserstory%2F402788988184&view=349baf7a-c63a-4fa4-a43b-2bb09274aad7) with one modification: if we know that all orgUnits in the current query have ancestors in the previous query, then we know that their related data has already been loaded. So it does not reload from the server in that case.
Quality notes
* Testing
* Chrome, FF, Edgium, Edge Legacy
* Calling server-side filtering has the same results as local filtering
* NOTE: there appears to be a bug on the server-side where applying a selectedOrgUnitId and a selectedSemesterId always returns no records
* Security: N/A
* Devops: N/A
* Docs: N/A
* Perf:
* One possible optimization which is not applied: if all …

US118248 Reload data from server if necessary

---

components/time-in-content-vs-grade-card.js
model/data.js
test/model/data.test.js

https://rally1.rallydev.com/#/detail/userstory/402804181236
There is a grey dotted horizontal line at the grade that is the avg grade for the data returned.
There is a grey dotted vertical line at the average time in content for the data returned.
If the line overlays with the grid line, it would be in front of the grid line.
Accessibility: n/a
Security: n/a
Devops: local app works as expected with test data
UX: demo with Kevin - done
@rohitvinnakota @hyehayes @anhill-D2L @johngwilkinson

US118260 TiC vs Grades avg lines

---

components/current-final-grade-card.js
components/summary-card.js
components/time-in-content-vs-grade-card.js
engagement-dashboard.js

https://rally1.rallydev.com/#/23525809118d/custom/12155517225?detail=%2Fuserstory%2F399914048420
**Quality Notes**
For now, I ended up using a flex design, so on wider screens, the graphs display side by side. We should have a discussion on whether we want to resize the charts themselves when we change the screen size. For now, the size of the cards is fixed. 
Tested on my laptop screen, a 27 inch monitor, and different browsers. Added 2 extra debug cards for comparison. 
security: n/a
perf: n/a
devops: n/a
ux/docs: Have screenshots for now, as mentioned, I think we should have further discussion on this. 
fyi @hyehayes @Vitalii-Misechko @MykolaGalian @anhill-D2L

Tweak layout

---

package.json

BSI won't build with the newer version because two other components use this lib on 0.0.x
Testing: ran via BSI with npm link; interactions worked as expected. Confirmed in package-lock that v0.0.4 was used.

revert mobx-lit package to match others in BSI

---

model/orgUnitAncestors.js
test/engagement-dashboard.test.js
test/model/orgUnitAncestors.test.js

This fixes a potential bug, possibly seen on Spark.
FYI @anhill-D2L @MykolaGalian  @Vitalii-Misechko

handle org units that aren't in the parents map

---

components/aria-loading-progress.js
components/chart/chart.js
components/current-final-grade-card.js
components/overdue-assignments-card.js
components/overlay.js
components/results-card.js
components/summary-card.js
components/time-in-content-vs-grade-card.js
engagement-dashboard.js
locales/en.js
test/.eslintrc.json
test/components/aria-loading-progress.test.js
test/components/current-final-grade-card.test.js
test/components/overlay.test.js
test/components/time-in-content-vs-grade-card.test.js
test/engagement-dashboard.test.js

[US118543](https://rally1.rallydev.com/#/detail/userstory/404486515748?fdp=true): [Engagement] Loading states
AC:
Add the spinners/grey cards/table into the UI for when the dashboard is loading as per the design
Out of scope of the story:
* Tab-navigation over dashboard's cards is a part of US120050 story. I believe that tab-navigation when loading is in-progress should be part of that story as well.
* Grey cards/table - skeleton components are [in active development](https://d2l.slack.com/archives/C0PHG3QB0/p1600085625042300). Should be implemented in a separate PR or story. 
* Unit tests
* Manual tests  
* Keyboard navigation
* Announcement when loading is started/finished. 
* Alerts are not accessible for screen reader via tab and arrow navigation.
* Alerts are not visible on the …

US118543 [Engagement] Loading states

---

components/chart/chart.js
components/current-final-grade-card.js
components/time-in-content-vs-grade-card.js
test/engagement-dashboard.test.js

Fix of 
* [Heading levels should only increase by one](https://dequeuniversity.com/rules/axe/3.5/heading-order?application=axeAPI)
* [Landmarks must have a unique role or role/label/title (i.e. accessible name) combination](https://dequeuniversity.com/rules/axe/3.5/landmark-unique?application=axeAPI)
```
---
Rule: heading-order
Impact: moderate
Heading levels should only increase by one (https://dequeuniversity.com/rules/axe/3.5/heading-order?application=axeAPI)
Issue target: d2l-insights-engagement-dashboard,d2l-insights-current-final-grade-card,d2l-labs-chart,h5
Context: <h5>Chart</h5>
Fix any of the following:
Heading order invalid
---
Rule: landmark-unique
Impact: moderate
Ensures landmarks are unique (https://dequeuniversity.com/rules/axe/3.5/landmark-unique?application=axeAPI)
Issue …
```

Fix accessiblity issues that was found implementing US118543 

---

components/current-final-grade-card.js
locales/en.js

[US118264](https://rally1.rallydev.com/#/detail/userstory/402807208416?fdp=true): [Engagement][Cards] Grades Hover Text
Quality notes: 
-> Tested on chrome, firefox, and edge
-> No changes to accessibility functionality since that relies on the `pointDescriptionFormatter` attribute
-> Tested with filters, tooltip values update as expected. 
fyi: @bemailloux @hyehayes @anhill-D2L @Vitalii-Misechko

Add hover behavior for current final grade

---

components/course-last-access-card.js
components/current-final-grade-card.js
locales/en.js

[US118262](https://rally1.rallydev.com/#/detail/userstory/402806125096?fdp=true): [Engagement][Cards] Course Access Hover Text
Quality notes:
Similar to current final grade
-> Tested on chrome, firefox, and edge
-> No changes to accessibility functionality since that relies on the pointDescriptionFormatter attribute
-> Tested with filters, tooltip values update as expected.
fyi: @bemailloux @hyehayes @anhill-D2L @Vitalii-Misechko

Add hover behavior for course last access

---

components/table.js
components/users-table.js
locales/en.js
model/data.js
test/components/table.test.js
test/components/users-table.test.js
test/model/data.test.js

Adds headers for courses, avg grade and avg time in content. Last system access and avg discussion activity will eventually exist, but are not targeted for this iteration.
Quality notes:
* Testing
* Responsive
* Browsers: Chrome, FF, Edgium, Legacy
* RTL
* Security, docs, perf: N/A
* UX
* A11y: NVDA reads out all the column names: `Column 1 Last Name, First Name | Column 2 Courses | Column 3 Average Grade | Column 4 Average Time in Content`
Screenshot
@johngwilkinson @Vitalii-Misechko @anhill-D2L @hyehayes

US117442 More users table headers

---

components/time-in-content-vs-grade-card.js
locales/en.js

[US118263](https://rally1.rallydev.com/#/detail/userstory/402807206872?fdp=true): [Engagement][Cards] TiC v Grades Hover Text
After a discussion with Kevin, it was agreed that we want the arrow of the tooltip to point to the midpoint of the quadrant. The tradeoff here is that the tooltip will not pop up if we hover at the edge of the chart, otherwise it works as expected. 
**Quality Notes**
Functional testing
Tested the following cases
-> No data in quadrant: Shows "0 users have x grade.."
-> Tested on edge, chrome, and firefox
-> Tooltip updates with filters
Accessibility
->No effect on accessibility 
Devops: local app works as expected with test data
UX: Went over design with Kevin
Security: n/a
fyi: @bemailloux @hyehayes @Vitalii-Misechko @anhill-D2L

TiC v Grades Hover Text

---

components/time-in-content-vs-grade-card.js

There was an issue with the ` this.series.name` attribute when clicking on the quadrants. This is because we were using shared tooltips. More info here:
https://www.highcharts.com/forum/viewtopic.php?t=19061
@bemailloux @hyehayes @anhill-D2L @Vitalii-Misechko

Fix issue with tic filter interaction

---

components/table.js
components/users-table.js
locales/en.js
model/data.js
model/fake-lms.js
package.json
test/components/course-last-access-card.test.js
test/components/results-card.test.js
test/components/table.test.js
test/components/users-table.test.js
test/model/data.test.js

Adds additional info to the name column in the users table.
Quality notes
* Testing
* Responsiveness - the table as a whole is wonky (and should be fixed along with the wonky cards) but this column in particular is good: the text resizes
* Browsers: Chrome, FF, Edgium, Legacy
* Security, perf, docs: N/A
* UX
* Checked with Kevin on text sizes (main text is d2l-body-standard, subtext is d2l-body-small)
* Checked with Megan that if a username is blank, it can appear as blank in the table (consistent with Class Engagement page)
* works in RTL
* a11y: still needs work. I need to ask Kevin what a screen reader user should hear for the column and the table during loading
Screenshots - Loaded
Loading: medium size screen
Loading: full size screen
@anhill-D2L @johngwilkinson @MykolaGalian

US120279 Users table name column

---

components/course-last-access-card.js
components/current-final-grade-card.js
components/overdue-assignments-card.js
components/time-in-content-vs-grade-card.js
consts.js
model/data.js
model/selectorFilters.js
test/components/applied-filters.test.js

@dlockhart informed me there are some circular dependencies in our repo:
```
..\insights-engagement-dashboard\model\data.js -> ..\insights-engagement-dashboard\model\selectorFilters.js -> ..\insights-engagement-dashboard\model\data.js
```
In general we want to avoid circular dependencies wherever possible, as they can lead to difficult-to-reproduce bugs if files get loaded in the wrong order.
Solution: put all consts that are used in multiple places in a separate dependency-less file.
Quality notes
* Testing
* Unit tests pass
* Playing around with the dashboard (including interactions) still works
* Running `npm run build` in BSI no longer reports this warning
* Security, perf, UX: N/A
* Docs: maybe I should write some? I dunno
@MykolaGalian @Vitalii-Misechko @anhill-D2L

Remove circular dependencies

---

model/data.js
package.json
test/components/users-table.test.js
test/model/data.test.js

Quality Notes
* functional
* user w. time and grade in two courses (NB: to get time in content, need to log in as the user - impersonation doesn't seem to work)
* users with no time in content or grades
* filtered by role so one or the other of the user's courses were in view; numbers update accordingly
* i18n: tried german and confirmed dots and commas get switched
* security: n/a
* performance: no significant change
* devops: n/a
* ux/docs
* uses standard d2l number/percent formatting
* screen-reader + keyboard works (need to use arrow keys from the last graph to reach the table)

US120515, US120514: add avg tic and grade to users table

---

engagement-dashboard.js

Issue: When some bar is selected in "Course Access" card for the first time, the filter button is drawn using "d2l-applied-filters". After that, I cannot select the last bar on this card. It can be selected only if the mouse goes outside the plot and then again clicking on this bar.   
The proposed solution is fix CSS for parent div container .d2l-insights-summary-container-applied-filters (https://stackoverflow.com/a/19221684/14336208).
However, due to the reservation of the minimum space for the container, the indent has increased.
UX: I showed it on demo after stand-up.
Previous PR: https://github.com/Brightspace/insights-engagement-dashboard/pull/72
Next story for that defect: https://rally1.rallydev.com/#/23525809118d/iterationstatus?detail=%2Fdefect%2F440857153012&sharedViewId=328666 …

Access interaction fix

---

components/chart/chart.js
components/course-last-access-card.js
engagement-dashboard.js

Related to #79 
I managed to trace the problem into HighCharts. 
When a bar in the chart is selected and the graphs are shifted down in the document the graphPosition is not updated in the pointer when the chart is not close to the top of the page. If the chart is visible from the top of the page or if you zoom out enough to see the top of the page then the chartPosition is updated. 
By reseting that state on every click the problem is resolved. 
Wondering your thoughts on this fix or if you think we should submit a PR directly to HighCharts.
@anhill-D2L  @bemailloux @rohitvinnakota @hyehayes

Remove space under filter and fix bar after selection DE40834

---

model/data.js

Yikes! Console logging in this getter shows that without the `computed` decoration, it's unsurprisingly getting called many many times per render (it gets called by the filter method for the corresponding card, so once per row, calculate the average of all the rows... so n^2).
FYI @bemailloux @MykolaGalian @NicholasHallman @Vitalii-Misechko

prevent massive amounts of recalculation

---

components/results-card.js
components/users-table.js
model/data.js
test/components/results-card.test.js
test/components/users-table.test.js
test/model/data.test.js
test/model/mocks.js

Just a refactor
Regression testing (local e2e): load page; apply role filter and grade filter and verify that users in table, calculated values, and results card change accordingly.

US119012: refactor: move user table logic out of Data

---

components/course-last-access-card.js
consts.js
engagement-dashboard.js
model/data.js
test/components/course-last-access-card.test.js
test/components/current-final-grade-card.test.js
test/model/data.test.js
test/model/mocks.js

Regression testing (local e2e):
* load page; use role and grade filter and confirm last access chart updates
* w. dummy data for last access, apply filter and confirm other views update
FYI @anhill-D2L @bemailloux @NicholasHallman @rohitvinnakota

US119012: refactor: move last access logic out of Data

---

components/discussion-activity-card.js
locales/en.js

[US118261](https://rally1.rallydev.com/#/detail/userstory/402806086044?fdp=true): [Engagement][Cards] Discussion Activity Hover Text
Quality Notes
-> Changed hover behavior so it doesn't create generate a ~shadow thing~ halo when hovering over slices to match the design here:
https://xd.adobe.com/view/cf5c5823-d1c3-47eb-45b6-8297bf92f944-b96d/screen/e6aa869d-2268-4f7f-a405-1d3c9f9a879b/
Functional testing
Tested the following cases
-> Tested on edge, chrome, and firefox
-> Data changes with filters
-> Data changes when filtering by clicking on legend
Accessibility
->No impact on accessibility. We have separate options for those 
Security: n/a
Perf testing
Devops: n/a
UX: 
fyi: @Vitalii-Misechko @MykolaGalian @NicholasHallman @hyehayes @anhill-D2L

Add hover text for discussion activity

---

engagement-dashboard.js
locales/en.js
package.json

[US118258](https://rally1.rallydev.com/#/detail/userstory/402800588876?fdp=true): [Engagement] Link to documentation
AC:
Hyperlink called "Learn More" and "Export to CSV" button.
Link out to https://community.brightspace.com/s/article/Brightspace-Performance-Plus-Analytics-Administrator-Guide in another tab.
UX demo: in progress
FYI @anhill-D2L @NicholasHallman @rohitvinnakota @johngwilkinson

US118258 Link to documentation 

---

components/table.js

Added screen reader accessibility to the user table sort arrows, reads out the sort order when the column header is focused if the header is sorted.

US120286 Table Sort Accessibility

---

components/current-final-grade-card.js
test/components/current-final-grade-card.test.js

The problem was that selections weren't triggering a change because `filter.selectedCategories` was not accessed inside `render()`, but in a callback that happened later.
Pattern that seems to avoid this kind of problem: whenever possible, the full state of the chart should be a function of the mobx state, with callbacks doing nothing but altering that state (which forces a call to render).
This would be easier if we weren't using the histogram module at all (it doesn't buy us much), but I didn't want to fiddle with the layout in switching to a column chart.
Quality Notes:
* functional
* e2e with canned and local LMS data
* select individual and multiple bars and check colouring
* clear and check colouring
* with canned data not including extremes (note: the histogram module only renders …

US119012: fix grades card selection colouring

---

components/tree-filter.js
components/tree-selector.js
locales/en.js
test/components/tree-filter.test.js
test/components/tree-selector.test.js

Quality Notes
* functional
* clear default view: semesters first, ou first
* select ous then clear (not default view)
* select ous deeper in three, then clear
* clear button is visible only when items are selected
* security, perf, devops: n/a
* ux/docs
- keyboard nav & screen-reader works
FYI @anhill-D2L @MykolaGalian @NicholasHallman @Vitalii-Misechko

US121664: clear button for ou filter

---

components/course-last-access-card.js
test/components/course-last-access-card.test.js

See #111 for general notes.
Quality Notes
* functional
* e2e and demo data
* select 0-valued and non-zero bars
* select single and several, including extremes
* with another filter on, select a bar that has a zero value, then clear the other filter so it is non-zero
* devops, security, perf: n/a
* ux/docs: last-clicked bar is not outlined anymore; does not affect keyboard navigation
FYI @anhill-D2L @bemailloux @MykolaGalian @rohitvinnakota

US119012: fix last course access selection colouring

---

components/discussion-activity-card.js

Solution: 
It looks like lit elements will make up for the lack of shadow dom in edge by applying the elements name as a css style to scope the styles to the component. However, if the element name overlaps with a class name that class (in this case, the card border) get's applied to all of the elements in the component! fun!

Fix Edge Legacy Discussion Summary

---

components/last-access-card.js
components/overdue-assignments-card.js
components/summary-card.js
locales/en.js

Quality Notes:
* functional
* w. Narrator and keyboard, navigate page
* tabbing to clickable summary number reads all the card text
* using up and down arrows to reach both clickable and non-clickable summary numbers reads all the card text
* screen reader does not read out any duplicate text in the summary body
* summary cards with filters can be enabled using the keyboard
* devops, perf, ux/docs, security: n/a
FYI @anhill-D2L @MykolaGalian @NicholasHallman @rohitvinnakota

US120050: screen reader support for summary cards

---

components/default-view-popup.js
components/expander-with-control.js

So the text doesn't get too close to the button.
Before:
After: 
(Yes the language in the rest of the dialog is wrong - I was just testing quickly)
FYI @NicholasHallman @Vitalii-Misechko @MykolaGalian @rohitvinnakota

Add margin to expander button

---

demo/index.html
engagement-dashboard.js
model/telemetry-helper.js
package.json
test/model/telemetry-helper.test.js

[US119022](https://rally1.rallydev.com/#/detail/userstory/408922032584?fdp=true): [Engagement] Page Load Telemetry
Each page load causes 4 API calls to Production Telemetry Service. Each event contains `EventBody.Object.Id` which is the same across these 4 calls. Telemetry records following metrics.
```JSON
[
"first-paint",
"first-contentful-paint",
"d2l.page.preFetch",
"d2l.page.timeToClient",
"d2l.page.webComponentsReady",
"d2l.page.domInteractive",
"d2l.page.load",
"d2l.page.server",
"d2l.page.download",
"d2l.page.domContentLoadedHandlers",
"d2l.page.tti"
]
```
[GRID web performance](https://docs.dev.d2l/index.php/GRID:_Web_Performance) especially pays attention to First Contentful Paint(_first-contentful-paint_) and Time to Interactive(_d2l.page.tti_).
[Examples of performance …

US119022 Page load telemetry

---

components/chart/chart.js
components/course-last-access-card.js
components/current-final-grade-card.js
components/histogram-card.js
components/time-in-content-vs-grade-card.js
test/components/current-final-grade-card.test.js

- Changed easing function to quadric easeOut
- Added reduced motion accessibility
- Converted histogram chart to column chart to fix animation problems (may be due to multiple data series?)
The grade card was converted from a histogram to a column chart because of animation troubles. Couldn't get them working for most of yesterday and decided to use Highcharts second example for histograms. 
Testing
- Verified using unit tests 
- And Manual testing to make sure that converting the table didn't break any of the mobx state management.
Performance
- N/A css and svg animations are hardware accelerated, and they don't run very often
UX
- Pending Demo, showed kevin propositions for different easing functions.
@johngwilkinson @anhill-D2L @bemailloux @rohitvinnakota @hyehayes

Enable all card animations

---

components/message-container.js
engagement-dashboard.js
locales/en.js
test/components/message-container.test.js

[US117901](https://rally1.rallydev.com/#/detail/userstory/399910079036?fdp=true): [Engagement] Errors - No data in filtered range
Based on earlier discussion during our meetings, I have the cards and charts not rendering when 0 users are returned. ~~It seems that we have some default functionality for the user table when no users are returned so I left that as is.~~ 
Demoed to Kevin and we agreed upon rendering just the message and no user table when there are 0 users returned. 
**Quality notes**
Tested on edge, firefox, chrome
Changing filters removes or recreates dialog as expected
LTR to RTL works as expected
Responsiveness works as expected
Accessibility: Text picked up by screen reader
Perf testing: n/a
Devops: n/a
fyi: @Vitalii-Misechko @MykolaGalian @NicholasHallman @hyehayes …

Add no results error message

---

components/course-last-access-card.js
components/current-final-grade-card.js
components/discussion-activity-card.js
components/overlay.js
components/summary-card.js
components/table.js
components/time-in-content-vs-grade-card.js
components/users-table.js
demo/index.html
engagement-dashboard.js
package.json
test/components/table.test.js
test/components/users-table.test.js
test/engagement-dashboard.test.js

Implementation Notes (optional)
Regression: The aria-hidden-focus Accessibility test needed to be disabled for the user-table because of the scroll wrapper.
Functional Testing
- Unit tests are still ✔ (except accessibility for above reason)
- Developed in Firefox and Chrome
- Tested for Edge Legacy
Performance
- N/A
Security
- N/A
Dev-Ops
- N/A
Cost
- N/A
Documentation
- N/A
UX
- Table has a min-width per column, to activate the table scroll buttons at lower widths and to prevent overflowing the whole page.
- The current grade chart now sits beside the summary cards at > 1200px 
- all the cards area  tiny bit smaller to fit the 615px break point requirement, cards are now 290px wide for summary and 590px for a chart.
- spacing between cards was changed to 10px
- stricter rules to the …

US121665 Breakpoints

---

test/components/table.test.js
test/components/users-table.test.js
test/engagement-dashboard.test.js

Ignore  `button-name` axe rule violation.
```
Rule: button-name
Impact: critical
Buttons must have discernible text (https://dequeuniversity.com/rules/axe/3.5/button-name?application=axeAPI)
Issue target: d2l-insights-engagement-dashboard,d2l-insights-users-table,d2l-insights-table,d2l-scroll-wrapper,.right,.d2l-table-circle-button
Context: <button class="d2l-table-circle-button" type="button"><d2l-icon icon="d2l-tier1:chevron-right"></d2l-icon></button>
Fix any of the following:
Element does not have inner text that is visible to screen readers
aria-label attribute does not exist or is empty
aria-labelledby attribute does not exist, references elements that do not exist or references elements that are empty
Element's default semantics were not overridden with role="presentation" …
```

Ignore  `button-name` axe rule violation

---

components/card-overlay.js
components/chart/chart.js
components/discussion-activity-card.js
components/overlay.js
components/summary-card.js
test/components/card-overlay.test.js
test/engagement-dashboard.test.js

[DE41152](https://rally1.rallydev.com/#/detail/defect/450306771184?fdp=true): [Engage] Discussion Activity shows spinner shifted to the left edge of the card
This PR introduces `d2l-insights-card-overlay`. This way we can show consistent skeletons for different card types
* Unit tests pass
* Verify look of the dashboard when it's loading
* Verify look of the dashboard when it's finished loading
* Responsive UI works
* Accessible (screen reader / keyboard nav)
* Browsers
* Chrome
* FF
* Edgium
* ~Edge Legacy N/A~
Before
After
FYI @anhill-D2L @MykolaGalian @rohitvinnakota @hyehayes @johngwilkinson

DE41152 Fix cards skeleton

---

components/summary-card.js

[DE41200](https://rally1.rallydev.com/#/detail/defect/450971805256?fdp=true): [Engagement] Font for clickable summary cards is wrong
A.C.
Font for clickable summary cards should be Lato
Tested in browsers (Windows 10 Chrome, Firefox, Edge)
@bemailloux  @hyehayes @Vitalii-Misechko @anhill-D2L @johngwilkinson

Font for summary cards

---

components/chart/chart.js
components/course-last-access-card.js
components/current-final-grade-card.js
components/overlay.js
components/summary-card.js
components/time-in-content-vs-grade-card.js
test/components/overlay.test.js

[DE41206](https://rally1.rallydev.com/#/detail/defect/451146798800?fdp=true): [Engage] Fix cards' and charts' skeleton look
FYI @anhill-D2L @MykolaGalian @rohitvinnakota @hyehayes @johngwilkinson 
* Unit tests pass
* Verify look of the dashboard when it's loading
* Verify look of the dashboard when it's finished loading
* Responsive UI works
* Accessible (screen reader / keyboard nav)
* Browsers
* Chrome
* FF
* Edgium
* ~Edge Legacy N/A~

DE41206 [Engage] Fix cards' and charts' skeleton look

---

model/data.js

I realized this was a one-liner. :)
Quality:
* functional
* first page load
* clear ou filter (no server hit): no skeletons/spinners
* clear semester filter: cards go to skeletons and spinners until load completes
* clear semesters first, then add and clear ous (all server hits): spinners and skeletons on each change
* ux/docs/devops/perf/security: n/a
FYI @bemailloux @MykolaGalian @NicholasHallman @rohitvinnakota

US122260: show loading indicators when going back to the server for data

---

README.md
test/components/expander-with-control.test.js

The test used to create an event-handler after a setTimeout call which attempted to make sure the click happened after the event-handler was attached. This looks like a possible race condition, and straightening it out by creating the promise before clicking (then awaiting it after) did fix the issue (see earlier commit). But there's also a utility, `oneEvent` we use elsewhere for this purpose, so I updated the code to use that.
Quality Notes: test change only

US121459: fix broken osx test

---

components/user-drill-view.js
demo/index.html
engagement-dashboard.js
locales/en.js

[US121773](https://rally1.rallydev.com/#/detail/userstory/449082079828?fdp=true): [Engagement][UserDrill] Create the page
FYI @anhill-D2L @MykolaGalian @rohitvinnakota @hyehayes @NicholasHallman 
Minimal working solution that would allow other developers to work on UserDrill in demo page.
What is in-progress (separate PR/PRs):
* ImmersiveNav as a part of engagement dashboard
* Navigation to the new page by clicking on user name
* Routing based on `page.js` that supports browser's Back button
* Page design refining
* Unit tests pass
* Manual tests
* The new page is available by default in demo page.
* `d2l-insights-engagement-dashboard` behavior is not changed when it's invoked from LMS

US121773 [UserDrill] Create the page

---

components/users-table.js
engagement-dashboard.js
model/exportData.js
test/components/users-table.test.js

Quality Notes:
- functional
- demo page: remove various columns, including all possible: renders as expected
- demo page: sort on columns where an earlier column is hidden
- demo page: export with hidden columns
- e2e: remove columns via API; render, sort, and export
- tested export with and without the discussions columns
- perf: no significant change
- devops: n/a
- security: n/a
- ux/docs: table seems to behave pretty well - but there is a story scheduled to adjust layout in any case
@anhill-D2L @MykolaGalian @rohitvinnakota @Vitalii-Misechko

US120705: show table columns according to user prefs

---

components/course-last-access-card.js
components/current-final-grade-card.js
components/discussion-activity-card.js
model/categoryFilter.js
model/urlState.js

A brief history...
The urlstate created a loop so when we saved the the persistenceValue it would call autorun to save the new state. Mobx is smart enough to know that the outcome will be the same as the url that was just set. However, when we set the persistent state for category filters (like the course access chart) the state was set by clearing all the categories and then turing on all the ones received from the url. autorun would get called for each of the individual category changes, which polluted the history and prevented the user from using the forward button in the browser.
My initial solution was simple, if we are popping the state, don't allow urlstate to save the state.
When mobx called the autorun it would change the dependent observable to the popping boolean. Because this …

Fix: Popping from history doesn't break mobx state tracking

---

engagement-dashboard.js
model/data.js
model/selectorFilters.js
test/engagement-dashboard.test.js
test/model/data.test.js
test/model/selectorFilters.test.js

I removed the role filter UI since it doesn't reflect this change, and it will shortly be replaced by the config page anyway.
I also removed the UrlState support from the role filter. Including it might make it possible to email links with specific role configs, but how that should interact with user prefs isn't clear - so it seemed safest just to remove it.
Quality Notes
- functional
- checked that configured list of roles is passed to server on load and data loads
- checked that data loads when there is no configured list of roles (PUT to config API without an `includeRoles` field)
- checked that configured roles are passed and data loads on reload from server (cleared semester filter)
- perf, security, devops: n/a
- ux/docs: role selection only via API for the moment, until the config …

US120705: apply role preference

---

components/dashboard-settings.js
components/immersive-nav.js
engagement-dashboard.js
locales/en.js
model/view-state.js
test/components/dashboard-settings.test.js
test/model/view-state.test.js

Sets up the settings page so that we can start working on the content. ~~It does not yet work with URL state.~~ It now works with URL state
Quality notes
* Testing
* It scrolls correctly when there is enough content on the page to cause scrolling
* Footer is still at the bottom of the page even if there isn't enough content to cause scrolling
* Tested w/ Chrome+NVDA
* D2L menus have interesting behaviour: you can't tab through the items but you can go through them with arrow keys. This is [expected behaviour](https://d2l.slack.com/archives/C0PHG3QB0/p1606404317237600). (@johngwilkinson you were right) 
* Settings page -> home page
* via browser back button
* via immersive nav back button
* via cancel / save and close buttons
* Home page -> settings page -> home page
* via browser back …

US120701 Settings page

---

components/card-selection-list.js
components/column-configuration.js
components/dashboard-settings.js
components/immersive-nav.js
components/table.js
components/users-table.js
engagement-dashboard.js
locales/ar.js
locales/cy-gb.js
locales/da.js
locales/de.js
locales/en.js
locales/es-es.js
locales/es.js
locales/fr-fr.js
locales/fr.js
locales/ja.js
locales/ko.js
locales/nl.js
locales/pt.js
locales/sv.js
locales/tr.js
locales/zh-tw.js
locales/zh.js

- unit tests will come in another PR, in the interest of making this available to UX for accessibility review
Quality notes
- Testing
- Browsers (Chrome, FF, Edgium, Edgacy)
- Accessibility (keyboard nav / screen reader - tested with NVDA/Chrome)
- RTL
- Responsive
- Test cases
- Loading: if settings exist for this user, it loads with those
- Display: after save and close, engagement dashboard uses the new settings
- Display: if cancel button is pressed, dashboard uses old settings
- Reload after saving: saved settings are persisted
- Security, devops, perf: N/A
- UX

US120707: column configuration ui

---

components/role-list.js

[US120704](https://rally1.rallydev.com/#/detail/userstory/437183105984?fdp=true): [Engage][Config] Move Role Filter
Main PR: https://github.com/Brightspace/insights-engagement-dashboard/pull/168
FYI @anhill-D2L @MykolaGalian @rohitvinnakota @hyehayes @NicholasHallman 
* Role list: shows only two column if there more than 13 roles
* Role list: does not show vertical scroll bar

US120704 [Engage][Config] Get rid of vertical scroll bar for role list

---

engagement-dashboard.js
test/engagement-dashboard.test.js

Fix a bad merge which was causing most columns in the users-table to disappear. + tests
Quality notes
* Testing
* Users table shows all columns if all columns are enabled in settings
* Users table shows only selector, name and courses columns if all columns are disabled in settings
* Users table shows correct columns if some are enabled in settings
* Security, devops, perf, docs, UX: N/A
@Vitalii-Misechko @NicholasHallman @rohitvinnakota @MykolaGalian

Fix bad merge

---

components/active-courses-table.js
components/column-configuration.js
components/users-table.js
demo/index.html
package.json
test/components/users-table.test.js

Quality Notes
- functional
- demo page: change timezone in html tag and check that times adjust
- lms: change timezone in account settings and verify times change (including a tz that pushed a date across a day boundary)
- devops: relies on new version of intl; will tag a release after this merges so that BSI can pick it up
- security/perf/ux: n/a
FYI @MykolaGalian @NicholasHallman @rohitvinnakota @Vitalii-Misechko

DE41591: use lms timezone setting for last accessed date

---

model/data.js
model/selectorFilters.js
model/urlState.js

Three small changes here:
1. fix handling of null semester filter in server response.
2. add `computed` to some getters in `Data` - not strictly necessary, but good practice, especially for the ones with corresponding setters (makes those into `action`s).
3. add `persistEmpty` to the semester filter so we can distinguish the default state from an all-filters-cleared state
Quality Notes
- functional (on local LMS)
- load default, check url
- clear all filters, check url
- clear all filters, refresh page (no default view popup or filters)
- clear query string and load (default view popup and filters)
- back and forward buttons with various filter settings including cleared semester filter
- devops/security/perf/ux: n/a
FYI @bemailloux @MykolaGalian @rohitvinnakota @Vitalii-Misechko

fix: semester filter state on reload data from server

---

components/discussion-activity-card.js

I was able to consistently reproduce the discussions pie chart not displaying by clicking back from the user drill page.
Before:
After:
FYI: @hyehayes @NicholasHallman @rohitvinnakota @MykolaGalian @Vitalii-Misechko

fix the bug where the discussions pie chart disappears

---

components/column-configuration.js
components/dashboard-settings.js
model/fake-lms.js

Right now visual diffing the demo page doesn't work.
This is because the golden screenshots include the last access columns which include the current time which is always changing.
Making the times in those columns static will make it so there are no differences in the visual diffs
Verified in my local LMS that the time values were not changed to what the demo page is using
FYI: @johngwilkinson @NicholasHallman @rohitvinnakota @Vitalii-Misechko @hyehayes

hardcode the timestamps so visual diffing works

---

components/card-selection-list.js
components/custom-toast-message.js
components/dashboard-settings.js
locales/en.js
test/components/card-selection-list.test.js
test/components/custom-toast-message.test.js

Adds a d2l-alert-toast message when trying to save and close an invalid set of settings. Currently, the message works for the last system access threshold value case but the functionality can be extended.
[US122868](https://rally1.rallydev.com/#/23525809118d/workviews/collection?detail=%2Fuserstory%2F459991179776%2Ftasks&itemRef=%2Fhierarchicalrequirement%2F459991179776&previousTokens=%2F23525809118d%2Fcustom%2F12155517225%3F&project=%2Fproject%2F23525809118&ref=%2Fhierarchicalrequirement%2F459991179776&relationship=tasks&fdp=true?fdp=true): [Engagement][Config] Settings page - error when saving fails
(The value in the screenshot's input is 233, not 23)
Screen reader: Clicking Save and close on an invalid system access value immediately triggers the alert and reads it out.
Responsiveness: …

Settings page - error when saving fails(Last System Access threshold value)

---

components/message-container.js
components/user-drill-courses-table.js
components/user-drill-view.js
engagement-dashboard.js
locales/en.js
test/components/user-drill-courses-table.test.js
test/components/user-drill-view.test.js

Shows error messages for various possible states.
* Testing (in progress)
* (Regression) It shows skeletons when loading
* (Regression) Both tables show data if there is data to show
* When user was not loaded due to invalid user id, displays "return to engagement dashboard" message
* When user was not loaded due to lack of permissions, displays "return to engagement dashboard" message
* When user was not loaded due to reload after specific user + filter combo, displays "return to engagement dashboard" message
* Return to engagement dashboard button ~~returns to home view~~ hard resets to default view
* When filters were applied such that no courses are in view, it hides both tables and displays "No data" message
* When filters were applied such that no active courses are in view, it …

Us122289+DE41776 user drill table errors

---

components/user-drill-courses-table.js
components/user-drill-view.js
test/components/user-drill-courses-table.test.js

Quality Notes
Before: on an org with no predicted grades, sorting on time-in-content did nothing because it was looking at current grade (one column over) instead (which happened to be null in my test data).
After: sorting works on all columns
Before: export always included predicted grade (even if not enabled)
After: export doesn't include predicted grade if not enabled (PM said either was fine, but this was equally easy along with the other changes)
Still testing:

US123012: off-by-one error when sorting user-drill courses table

---

components/applied-filters.js
components/dropdown-filter.js
components/tree-selector.js
package.json
test/components/applied-filters.test.js
test/components/dropdown-filter.test.js
test/components/semester-filter.test.js

Moving to `facet-filter-sort` version 4, which renamed all the components, files and events to indicate these components are in labs - no functionality changes. This version is also published to npm, which cleans up the `package.json` entry.
This needs to be merged at the same time as the PRs in `my-courses` (https://github.com/Brightspace/d2l-my-courses-ui/pull/882), `common` (https://github.com/BrightspaceHypermediaComponents/common/pull/43) and `discovery-fra` (https://github.com/Brightspace/discovery-fra/pull/305) to avoid any BSI downtime.

Update the major facet-filter-sort version

---

components/courses-legend.js

This fixes an AC regression with the user-drill legend.
Clicking on a legend item for the first time now "focuses" that course, subsequent clicks to other courses now toggle those courses on as well.

Focus Course on First Legend Item Click

---

model/dataApiClient.js
test/model/dataApiClient.test.js

We saw this issue on Spark.
Quality Notes
- functional: local e2e with and without trailing slash in metron config
- security, perf, devops, ux/docs: n/a
I looked for a lib to do this, but the one I found that looked good, url-join, doesn't seem to support esm imports - at least, I couldn't figure it out.
FYI @bemailloux @MykolaGalian

fix 401 when metron endpoint has a trailing slash

---

components/chart/chart.js
locales/ar.js
locales/cy-gb.js
locales/da.js
locales/de.js
locales/en.js
locales/es-es.js
locales/es.js
locales/fr-fr.js
locales/fr.js
locales/ja.js
locales/ko.js
locales/nl.js
locales/pt.js
locales/sv.js
locales/tr.js
locales/zh-tw.js
locales/zh.js

Originally we tried to have these symbols "translated", but the translators didn't understand what we wanted to do, and did nothing. (Except in zh where they used the _wrong_ symbol.)
Solution: use the intl library instead.
Quality notes:
* Testing: see screenshots
* Devops: this will be going into 20.21.03 as well
* Perf, security, UX, docs: N/A
Screenshots (demo page)
* English
* German
* French
* Spanish
* Spanish (Mexico) - same symbols as English
* Chinese
@NicholasHallman @anhill-D2L

Use intl library to get decimal and thousands separator symbols

---

components/user-drill-courses-table.js
components/user-drill-view.js
demo/index.html
engagement-dashboard.js
package.json
test/components/user-drill-courses-table.test.js

Quality notes
* Testing
* Table render [Draco LMS - E2E]
* NB: Changes to show predicted grade col are applied without having to reload the page (but changes to s3Enabled are not)
* Sorting [Demo page]
* Export [Draco LMS - E2E]
* Security, perf, devops: N/A
* Demo: demoed
* Docs: see previous PR (#484)
FYI @NicholasHallman @anhill-D2L

US123807 Apply predicted grade col setting to table

---

components/immersive-nav.js
components/user-selector.js
engagement-dashboard.js
locales/en.js
model/view-state.js
test/model/view-state.test.js

Quality Notes
- functional
- click on Insights Portal tile for Learner Engagement Dashboard: loads as expected (image below)
- hit f5; reloads user selector page
- click on "Back to Insights Portal": returns to insights portal
- click on tile for Engagement Dashboard; goes to regular engagement dashboard
- perf
- does not try to load dashboard data when hitting user selector
- security, ux/docs, devops: n/a
FYI @Vitalii-Misechko @anhill-D2L

US123549: stub learner dashboard entrance

---

components/immersive-nav.js
components/user-selector.js
locales/en.js
test/model/view-state.test.js

[US126962](https://rally1.rallydev.com/#/23525809118d/iterationstatus?detail=%2Fuserstory%2F521050018628&sharedViewId=328666453148&view=dc9e7043-1cf6-486d-a4aa-3a212976e789&fdp=true?fdp=true): [Engagement] Learner Engagement Dashboard Page
This PR includes only `search` input and its behavior. It was made to make early integration with John's branch
* Functional Testing 
* The page shows skeleton list of 10 items when a user hits the search button
* Security, devops, perf: N/A
* UX and docs
~* [ ] Demo to Kevin~ Will demo when I finish all components of the story
FYI @NicholasHallman @anhill-D2L

US126962 [Engagement] Learner Engagement Dashboard Page. Search

---

components/applied-filters.js
components/content-view-histogram.js
components/course-last-access-card.js
components/current-final-grade-card.js
components/discussion-activity-card.js
components/last-access-card.js
components/overdue-assignments-card.js
components/time-in-content-vs-grade-card.js
locales/en.js
test/components/applied-filters.test.js
test/components/content-view-histogram.test.js
test/components/course-last-access-card.test.js
test/components/discussion-activity-card.test.js

Continuation of #533 
Implementation Notes
Moved the axe description from the charts into the filter for 
- Content View
- Discussion Activity
- Course Access
- Time in Content vs Grade
Also, created descriptive titles and moved merge functions of the above charts into their filters.
Quality Notes
Testing
- Updated tests to check the accessible description in the filters
- Manually tested descriptive titles
- Course access merged categories and vague tag
- Time in content categories
- Discussion activity categories and vague tag
- Content view category merging, 0 and infinity
UX - Descriptive titles for filter tags
Docs - N/A
Performance - N/A
Security - N/A
FYI: @anhill-D2L @Vitalii-Misechko @hyehayes

Detailed Filter Tags 2 US126898

---

components/courses-legend.js
components/expander-with-control.js
test/components/card-selection-list.test.js
test/components/column-configuration.test.js
test/components/courses-legend.test.js
test/components/expander-with-control.test.js
test/components/user-level-card-selection-list.test.js

* Functional Testing 
* Course legend can be selected with keyboard
* Course legend allows toggling a course with keyboard/mouse
* Engagement Dashboard Default View dialog allows selecting expand arrow.
* Engagement Dashboard Default View dialog allows expanding/contraction the courses list with keyboard/mouse
* NVDA works the same on Course legend and Engagement Dashboard Default View dialog
* Security, devops, perf: N/A
* UX and docs
@NicholasHallman

Fixed a bunch of AXE tests that started to fail after axe-core 4.2.0 is released

---

model/dataApiClient.js

[US127900](https://rally1.rallydev.com/#/23525809118d/search?detail=%2Fuserstory%2F23c9cc05-07a5-4a2d-95c2-fd72db5d0af8&keywords=Remove%20unused&fdp=true?fdp=true): [Engagement] Remove unused LMS metrics code
Related PRs: 
https://github.com/Brightspace/lms/pull/10258
https://github.com/Brightspace/lms/pull/10321
* Functional Testing 
* Security, devops, perf: N/A
* UX and docs : N/A
FYI @anhill-D2L @hyehayes @NicholasHallman

US127900 [Engagement] Remove unused LMS metrics code. bdp-query overrides the metrics param to false

---

package.json

insights-engagement-dashboard is using puppeteer version 8
and visual-diff version 3.0.0 is using puppeteer version 7
and visual-diff version 4.0.0 is using puppeteer version 8
NPM install failed due to mismatch of puppeteer versions, change the version of visual-diff from 3.0.0 to 4.0.0 fixed the issue for me 
Functional Testing
NPM install works 
Performance
NA
Security
NA
Dev-Ops
NA
Cost
NA
UX
NA
FYI @anhill-D2L  @hyehayes @johngwilkinson @Vitalii-Misechko

fix the version for puppeteer to match the version with visual-diff

---

.github/workflows/notify.yml
locales/zh.js

It worked!
Now that we know the webhook fires properly I am limiting the job to only trigger when the brightspace-bot triggers the action as was Marks suggestion.

Fix Notify and Test and Add Bot Limit

---

.github/workflows/ci.yml

We are planning to bump the version of Puppeteer used in visual-diff and so this PR is to bump the node version to the current LTS version.

Bump node version used in GitHub actions

---

components/engagement-dashboard-errors.js
engagement-dashboard.js
locales/en.js
model/data.js
test/components/engagement-dashboard-errors.test.js
test/engagement-dashboard.test.js

We now show an error message if the user's roles that they previously had selected are now excluded by the config variables.
The buton on this error message opens the settings page when pressed (reuses the same code as the settings button in the collapsable menu)
This change also observes the differences between a new user with no roles selected seeing the dashboard for the firest time; where the lms returns all results, and a user whos selected roles have been disabled in the config; in which the lms returns null.
Quality Notes
Testing
- Tested on demo
- Tested on Local LMS with mock bdp query
- Tested on Local LMS with bdp Draco stack
UX
- Wording approved by kevin
All others N/A
FYI: @Brightspace/draco-vis

No Roles Error Messaging
