README.md

Token is not required for public repo like this
FYI @rohitvinnakota @anhill-D2L @hyehayes @johngwilkinson

Update link on travis badge

---

components/semester-filter.js
components/simple-filter.js
engagement-dashboard.js
locales/en.js
model/fake-lms.js
model/lms.js
test/components/semester-filter.test.js

[US117427](https://rally1.rallydev.com/#/detail/userstory/396954104020?fdp=true): [Engagement][Filters] Semester
Back-end API PR: https://git.dev.d2l/projects/CORE/repos/lms/pull-requests/14230/overview
FYI @johngwilkinson 
* Test cases - [WIP]
* Browsers
* Unit tests added

US117427 [Engagement][Filters] Semester

---

components/semester-filter.js
locales/en.js
test/components/semester-filter.test.js

[US117427](https://rally1.rallydev.com/#/detail/userstory/396954104020?fdp=true): [Engagement][Filters] Semester
JFYI @anhill-D2L @MykolaGalian @rohitvinnakota @hyehayes
- Unit tests
- Verified manually

Semesters show up as "OrgUnitName (Id: OrgUnitId)"

---

components/chart/chart.js
components/current-final-grade-card.js
karma.sauce.conf.js
locales/en.js

Quality Notes
* functional
* e2e w. LMS
* first load (data contains final grades): histogram appears
* select a course with no final grades: message appears
* select a course with some final grades: histogram appears
* security: n/a
* perf: n/a
* devops: n/a
* ux/docs: approved via Slack

US118249: tree filter bug fix test (no selected ids case)

---

components/dropdown-filter.js
components/ou-filter.js
components/role-filter.js
components/semester-filter.js
components/tree-filter.js
engagement-dashboard.js
model/data.js
model/fake-lms.js
model/lms.js
model/selectorFilters.js
test/components/dropdown-filter.test.js
test/components/ou-filter.test.js
test/components/semester-filter.test.js
test/components/tree-filter.test.js
test/model/data.test.js

FYI @anhill-D2L @MykolaGalian @rohitvinnakota 
Quality Notes: see https://github.com/Brightspace/lms/pull/1450

US117438: default view; filter ou tree by semester

---

model/lms.js
test/components/role-filter.test.js
test/model/lms.test.js

Quality: roles filter shows roles as expected
FYI @bemailloux @MykolaGalian @NicholasHallman  @Vitalii-Misechko

US119525: use new roles api (only need insights portal perm)

---

model/data.js
test/components/users-table.test.js
test/model/data.test.js

[US120513](https://rally1.rallydev.com/#/detail/userstory/435482082300?fdp=true): [Engagement][UserTable] Course(s)

Add course count to user table

---

components/current-final-grade-card.js
locales/en.js

Quality Notes:
* functional
* tried in English and Arabic (no translations yet, but positioning works)
* security: n/a
* perf: n/a
* devops: need to pick up translation during cert
* ux/docs: Kevin-approved

DE40492: axis titles for Current Grade

---

model/data.js

As for master. This could be a significant performance issue given tens of thousands of records, so I figure we should certfix it.
Proposing to merge to r20.20.11 branch so when we ship translations, this fix will get picked up too.
FYI @MykolaGalian @NicholasHallman @rohitvinnakota @Vitalii-Misechko

prevent massive amounts of recalculation (cert fix from master)

---

components/applied-filters.js
locales/en.js

Previous PR: https://github.com/BrightspaceUILabs/facet-filter-sort/pull/74
Local copies of BSI will have to be updated for this to appear.
Quality
* Approved by Kevin
FYI @johngwilkinson @rohitvinnakota @NicholasHallman @anhill-D2L

US120434 Applied filters label change

---

engagement-dashboard.js

A correction after standup demo. Now help link opens in a new tab.
FYI @anhill-D2L @Vitalii-Misechko @rohitvinnakota @johngwilkinson

Help link opens in new tab

---

locales/fr-fr.js

serge changed the casing in a variable name; this fixes it

fix variable name in fr-fr translation

---

README.md

Add telemetry documentation to README.md
FYI @rohitvinnakota @MykolaGalian @johngwilkinson @NicholasHallman

Add telemetry documentation to README.md

---

karma.sauce.conf.js
test/model/telemetry-helper.test.js

Fix flaky test for Safari
FYI @rohitvinnakota @MykolaGalian @johngwilkinson @NicholasHallman

Fix flaky test for Safari

---

components/current-final-grade-card.js
test/components/current-final-grade-card.test.js

[DE41079](https://rally1.rallydev.com/#/detail/defect/449146359320?fdp=true): [Engagement] Current Grades uniqueness
Functional:
Local App works as expected with test data.
Accessibility: n/a
Security: n/a
Devops: n/a
UX: demo - n/a
FYI @rohitvinnakota @NicholasHallman @Vitalii-Misechko @anhill-D2L @johngwilkinson

Current Grades uniqueness

---

README.md

FYI @anhill-D2L @MykolaGalian @NicholasHallman @Vitalii-Misechko

add versioning scheme to README

---

demo/index.html
engagement-dashboard.js
test/engagement-dashboard.test.js

Quality Notes:
* functional: demo & e2e (show and hide cards using prefs API)
* security: n/a
* perf: n/a
* ux/docs: n/a (layout is wonky, but there's another story for that)
* devops: requires latest LMS change or all the cards will be hidden
Still to come: user table columns, last access threshold, and roles

US120705: show cards according to user prefs

---

components/tree-filter.js

This is a revert of my changes

Fix: Explicit tree filter appearing in url state

---

components/immersive-nav.js

[US121773](https://rally1.rallydev.com/#/detail/userstory/449082079828?fdp=true): [Engagement][UserDrill] Create the page
FYI @anhill-D2L @MykolaGalian @rohitvinnakota @hyehayes @johngwilkinson 
* Unit tests
* Manual tests
* Immersive nav updates its back button's text when a user navigates to the user drill page

US121773  Fix immersive nav is not updated when a user navigates between views

---

components/table.js
components/user-drill-view.js
components/users-table.js
locales/en.js
test/components/table.test.js

[US121773](https://rally1.rallydev.com/#/detail/userstory/449082079828?fdp=true): [Engagement][UserDrill] Create the page
FYI @anhill-D2L @MykolaGalian @rohitvinnakota @hyehayes @johngwilkinson 
This PR allows users to navigate to user drill page with keyboard key (ENTER). It also improve responsiveness of UI
* Unit tests
* Manual tests
* User able to open user drill page by hitting ENTER-key 
* Sreenreader (NVDA + Chrome) reads `Open user's page for {userName}`
Pic 1
Pic 2
Pic 3

US121773 Fix accessibility and responsiveness

---

components/dashboard-settings.js
engagement-dashboard.js
model/lms.js
test/model/lms.test.js

Quality Notes
- functional
- visit settings page, hit save, and confirm that the expected request is sent (nothing else is hooked up yet)
- security: n/a
- devops: n/a
- perf: n/a
- ux/docs: n/a

US120707: hook up settings props and save to LMS

---

package.json

[DE41199](https://rally1.rallydev.com/#/detail/defect/450971796436?fdp=true): [Engagement] Default view popup looks weird on small screens
https://github.com/BrightspaceUI/core/pull/966

fix for d2l-dialog

---

test/components/column-configuration.test.js
test/components/dashboard-settings.test.js

Quality Notes: just unit tests :)
Any coverage we would want to add here?
FYI @anhill-D2L @MykolaGalian @NicholasHallman @rohitvinnakota

US120707: settings unit tests

---

components/user-drill-view.js
engagement-dashboard.js

This pr makes the email callback window appear when you click on the email button in the user drill
- Verified it works by going into my local LMS, selecting a user, and clicking the button
- The result is the window opening and the user's email appearing in the Bcc.
FYI @MykolaGalian @anhill-D2L @rohitvinnakota @johngwilkinson

User Drill Email - US121803

---

components/applied-filters.js

This is one way we can fix it, but it may be better if we submit a pr directly to the component. Thoughts?
https://rally1.rallydev.com/#/23525809118d/workviews?detail=%2Fdefect%2F459133385892&fdp=true&view=349baf7a-c63a-4fa4-a43b-2bb09274aad7

Fix: Applied Filters isn't Keyboard Accessible

---

README.md
karma.sauce.conf.js

It's kind of wordy, but the deployment process is kind of complicated. Let me know if the steps can actually be followed and/or if I'm missing anything.
FYI @Vitalii-Misechko @MykolaGalian @hyehayes

Deployment how-to

---

components/user-drill-view.js

Implementation notes
This is the release cut with an extra commit to hide the alert message for prd.

R20.21.02 + hide alert unless demo

---

.github/workflows/ci.yml
.travis.yml
test/components/user-drill-view.test.js
test/engagement-dashboard.test.js
test/model/data.test.js
test/tools.js

Dragon Slayer. Migrate the travis jobs to github actions
Once merged we can disable travis on this repo
FYI @anhill-D2L @MykolaGalian @bemailloux  @hyehayes

Migrate Tests from Travis to GHActions

---

components/user-drill-courses-table.js
components/users-table.js
model/fake-lms.js
model/sorts.js

A little cleanup so we don't need to reuse the same functions everywhere. The mixin adds the needed table properties so the table updates when it detects a sort change. The sorting functions are defined as an array in the constructor which is much easier to read. Finally the sorts have been named so they can be easily added. 
Functional Tests
- Behavior is maintained, all tests passing.
- Manual tests side by side with master are the same
All others N/A

Refactor Table Sort as a Mixin, supply sort functions for ease of use

---

components/access-trend-card.js
components/content-views-card.js

Fix interaction user chart with legend

Fix interaction user chart with legend

---

components/access-trend-card.js
components/content-views-card.js

FYI @MykolaGalian @Vitalii-Misechko

merge interaction fix to release branch

---

components/user-drill-view.js

Fix spinners for user cards
@johngwilkinson  @anhill-D2L @bemailloux

Fix spinners for user cards

---

model/dataApiClient.js

* Functional Testing 
* E2E tests on Draco LMS. No errors for main page and user drill page of Engagement Dashboard.
* Security, devops, perf: N/A
* UX and docs
FYI @anhill-D2L @hyehayes @johngwilkinson @NicholasHallman @bemailloux @MykolaGalian

Fix url concatination logic for metron logic

---

components/chart/chart.js
locales/ar.js
locales/cy-gb.js
locales/da.js
locales/de.js
locales/en.js
locales/es-es.js
locales/es.js
locales/fr-fr.js
locales/fr.js
locales/ja.js
locales/ko.js
locales/nl.js
locales/pt.js
locales/sv.js
locales/tr.js
locales/zh-tw.js
locales/zh.js

Contains changes from #443 and #444

Translations 20.21.03

---

components/time-in-content-vs-grade-card.js

Quality notes: quadrant toggling and tooltips work now; accessibility works to (tested with Narrator)

bugfix: tic midpoints

---

.github/labeler.yml
.github/notify.sh
.github/workflows/label.yml
.github/workflows/notify.yml
locales/da.js
locales/zh.js

Removes the labeler action and replaces it with a webhook action.
Placing a webhook into this repo's SLACK_WEBHOOK secret will push a webhook to that slack channel when
- a pull request is opened
- and there have been changes to locale

Notify Slack Webhook on Locale Change
